# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: ivonne.martinez@skewthescript.org
author_name: Ivonne Martinez
data_format: string
file_extension: ''
has_binder: true
has_settings: true
kind: frontend
labextension_name: jupytereverywhere
mimetype: ''
mimetype_name: ''
project_short_description: A Jupyter extension for k12 education
python_name: jupytereverywhere
repository: https://github.com/JupyterEverywhere/jupyterlite-extension
test: true
viewer_name: ''

