name: Build the jupyterlite-extension wheel and sdist

runs:
  using: 'composite'
  steps:
    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@affc83be6020d529b9368cd4d63e467877606600 # v1

    - name: Install dependencies
      shell: bash
      run: python -m pip install -U "jupyterlab>=4.0.0,<5"

    - name: Restore Playwright browsers cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: /home/runner/.cache/ms-playwright
        key: playwright-browsers-${{ runner.os }}-v1
        restore-keys: |
          playwright-browsers-${{ runner.os }}-

    - name: Build the extension
      shell: bash
      run: |
        set -eux
        python -m pip install .[test]

        jupyter labextension list
        jupyter labextension list 2>&1 | grep -ie "jupytereverywhere.*OK"
        JLAB_BROWSER_TYPE=firefox python -m jupyterlab.browser_check

    - name: Package the extension
      shell: bash
      run: |
        set -eux

        pip install build
        python -m build
        pip uninstall -y "jupytereverywhere" jupyterlab

    - name: Upload extension packages
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: extension-artifacts
        path: dist/jupytereverywhere*
        if-no-files-found: error
