name: xeus-kernels
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  # https://github.com/jupyter-xeus/xeus-r/commit/094d4e9d87b367f93c92792eee2950c89a171c0c
  # Add https://github.com/jupyter-xeus/xeus-r/pull/161 until it is released
  - git+https://github.com/jupyter-xeus/xeus-r.git@094d4e9d87b367f93c92792eee2950c89a171c0c
  - numpy
  - pandas
  - scipy
  - seaborn
  - matplotlib
  - scikit-learn
  - r-base
  # -r-tidyverse is not available yet due to upper pin on r-base, and
  # older r-base versions are not available on emscripten-forge, so we
  # install some of the tidyverse packages individually (except for
  # r-lubridate)
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-readr
  - r-purrr
  - r-tibble
  - r-stringr
  - r-forcats
  - r-coursekata
  - r-neuralnet
