name: Build the jupyterlite app

inputs:
  mode:
    description: '"test" or "prod"'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: '3.11'

    - name: Install micromamba
      uses: mamba-org/setup-micromamba@b09ef9b599704322748535812ca03efb2625677b # v2.0.5

    - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
      with:
        name: extension-artifacts

    - name: Install the dependencies
      shell: bash
      run: |
        cd lite
        pip install -r requirements.txt

    - name: Install Jupyter Everywhere extension
      shell: bash
      run: |
        pip install jupytereverywhere*.whl

    - name: Install jlpm
      shell: bash
      run: |
        set -eux
        python -m pip install "jupyterlab==4.5.0a3"

    - name: Build the JupyterLite app in ${{ inputs.mode }} mode
      env:
        MATRIX_MODE: ${{ inputs.mode }}
      shell: bash
      run: |
        cd lite
        if [[ "${MATRIX_MODE}" == "prod" ]]; then
          echo "Building JupyterLite app in production mode"
          bash ../.github/inject-gh-pages-config.sh
        else
          echo "Building JupyterLite app in test mode"
          bash ../ui-tests/inject-test-config.sh
        fi
        cd ..
        jlpm install
        jlpm build:all

    - name: Upload artifact (${{ inputs.mode }})
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: lite-app-${{ inputs.mode }}
        path: ./dist
        if-no-files-found: error

    - name: Upload GitHub Pages artifact for production mode
      if: inputs.mode == 'prod'
      uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
      with:
        path: ./dist

    - name: Leave instructions for testing
      if: inputs.mode == 'prod'
      shell: bash
      run: |
        echo "### JupyterLite App is ready" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo 'To test it locally, download the `lite-app-prod` artifact and run' >> $GITHUB_STEP_SUMMARY
        echo '```bash' >> $GITHUB_STEP_SUMMARY
        echo "rm -r lite-app-prod" >> $GITHUB_STEP_SUMMARY
        echo "unzip lite-app-prod.zip -d lite-app" >> $GITHUB_STEP_SUMMARY
        echo "cd lite-app" >> $GITHUB_STEP_SUMMARY
        echo "python -m http.server -b 127.0.0.1" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo 'And navigate to http://127.0.0.1:8000/' >> $GITHUB_STEP_SUMMARY
        echo 'Press ctrl + c to stop the server.' >> $GITHUB_STEP_SUMMARY
