name: Add issues to Quansight project

on:
  issues:
    types:
      - opened

permissions: {}

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/JupyterEverywhere/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
